version: 2
updates:
- package-ecosystem: nix
  directory: /
  cooldown:
    default-days: 7
  schedule:
    interval: weekly
    day: monday
    time: '03:00'
    timezone: Etc/UTC
- package-ecosystem: github-actions
  directory: /
  cooldown:
    default-days: 7
  schedule:
    interval: weekly
    day: monday
    time: '03:00'
    timezone: Etc/UTC
