name: Tests and formatters
on:
  pull_request:
  push:
    branches: [main]
permissions:
  contents: read
jobs:
  code-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - uses: DeterminateSystems/nix-installer-action@c5a866b6ab867e88becbed4467b93592bce69f8a # v21
    - run: nix flake check
  readme-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - uses: docker://pandoc/core:3.1
      with:
        args: >-
          --columns=80
          --standalone
          --from=gfm
          --to=gfm
          --output=README.pan.md
          README.md
    - name: Compare README.md with its regenerated version
      run: diff README.md README.pan.md
